// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exercicio_ef;

#nullable disable

namespace exercicio_ef.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20231221165145_migration001")]
    partial class migration001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exercicio_ef.models.Caderno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("cadernos");
                });

            modelBuilder.Entity("exercicio_ef.models.Registro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cadernoId")
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("cadernoId");

                    b.ToTable("registros");
                });

            modelBuilder.Entity("exercicio_ef.models.Registro", b =>
                {
                    b.HasOne("exercicio_ef.models.Caderno", "caderno")
                        .WithMany("registros")
                        .HasForeignKey("cadernoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("caderno");
                });

            modelBuilder.Entity("exercicio_ef.models.Caderno", b =>
                {
                    b.Navigation("registros");
                });
#pragma warning restore 612, 618
        }
    }
}
